"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['/Users/Leo/Documents/ej_frm.py']
OPTIONS = {
 'iconfile':'/Users/Leo/Documents/home.icns',
}
setup(
 app=APP,
 options = {'py2app': OPTIONS},
 setup_requires=["py2app"],
)
